import { APP_ROUTES } from "@/utils/routes";
import {} from "react-icons/md";

const menuItems = {
  items: [
    {
      id: "Dashboard",
      title: "Dashboard",
      type: "single",
      url: APP_ROUTES.home,
      icon: "ic:twotone-space-dashboard",
    },
    {
      id: "daily-dashboard",
      title: "Daily Dashboard",
      type: "single",
      url: APP_ROUTES.home,
      icon: "clarity:dashboard-line",
    },
    {
      id: "declare-results",
      title: "Daily Results",
      type: "single",
      url: APP_ROUTES.home,
      icon: "carbon:report",
    },
    {
      id: "deposit-section",
      title: "Deposit Section",
      type: "collapse",
      url: "",
      icon: "ph:hand-deposit-fill",
      childrens: [
        {
          id: "deposit-sheet",
          title: "Deposit Sheet",
          type: "single",
          url: "",
          icon: "bi:file-spreadsheet",
        },
        {
          id: "manual-deposit",
          title: "Manual Deposit",
          type: "single",
          url: "",
          icon: "mdi:instant-deposit",
        },
      ],
    },
    {
      id: "withdraw-section",
      title: "Withdraw Section",
      type: "collapse",
      url: "",
      icon: "hugeicons:bitcoin-withdraw",
      childrens: [
        {
          id: "withdraw-sheet",
          title: "Withdraw Sheet",
          type: "single",
          url: "",
          icon: "bx:money-withdraw",
        },
        {
          id: "manage-withdraw-request",
          title: "Withdraw Request",
          type: "single",
          url: "",
          icon: "uil:money-withdraw",
        },
      ],
    },
    {
      id: "report-section",
      title: "Report Section",
      type: "collapse",
      url: "",
      icon: "mdi:file-report-outline",
      childrens: [
        {
          id: "sales-report",
          title: "Sales Report",
          type: "single",
          url: "",
          icon: "tabler:report-money",
        },
        {
          id: "customer-sales-report",
          title: "Customer Sales Report",
          type: "single",
          url: "",
          icon: "mdi:report-box-outline",
        },
        {
          id: "all-transactions",
          title: "All Transactions",
          type: "single",
          url: "",
          icon: "hugeicons:money-bag-02",
        },
      ],
    },
    {
      id: "manage-market",
      title: "Manage Market",
      type: "single",
      url: "",
      icon: "bi:graph-up-arrow",
    },
    {
      id: "manage-users",
      title: "Manage Users",
      type: "single",
      url: "",
      icon: "ph:users-duotone",
    },
    {
      id: "user-balance",
      title: "User Balance",
      type: "single",
      url: "",
      icon: "tdesign:money",
    },
    {
      id: "market-chart-data",
      title: "Market Chart Data",
      type: "single",
      url: "",
      icon: "ep:data-line",
    },
    {
      id: "daily-result",
      title: "Daily Result",
      type: "single",
      url: "",
      icon: "carbon:result-old",
    },
    {
      id: "all-bids",
      title: "All Bids",
      type: "single",
      url: "",
      icon: "solar:money-bag-bold",
    },
    {
      id: "all-market-results",
      title: "All Market Results",
      type: "single",
      url: "",
      icon: "icon-park-outline:market-analysis",
    },
    {
      id: "bid-revert",
      title: "Bid Revert",
      type: "single",
      url: "",
      icon: "mage:money-exchange",
    },
    {
      id: "send-notification",
      title: "Send Notification",
      type: "single",
      url: "",
      icon: "basil:notification-on-outline",
    },
    {
      id: "rate-manage",
      title: "Rate Manage",
      type: "single",
      url: "",
      icon: "mdi:cash-100",
    },
    {
      id: "settings",
      title: "Settings",
      type: "collapse",
      url: "",
      icon: "solar:settings-outline",
      childrens: [
        {
          id: "profile-settings",
          title: "Profile Settings",
          type: "single",
          url: "",
          icon: "gg:profile",
        },
        {
          id: "how-to-pay",
          title: "How To Pay",
          type: "single",
          url: "",
          icon: "mingcute:question-line",
        },
        {
          id: "slider",
          title: "Slider",
          type: "single",
          url: "",
          icon: "bx:slider-alt",
        },
        {
          id: "main-settings",
          title: "Main Settings",
          type: "single",
          url: "",
          icon: "carbon:settings-edit",
        },
      
      ],
    },
    {
      id: "main-market-number",
      title: "Main Market Number",
      type: "collapse",
      url: "",
      icon: "fluent:book-number-24-filled",
      childrens: [
        {
          id: "single-digit",
          title: "Single Digit",
          type: "single",
          url: "",
          icon: "tabler:number-1",
        },
        {
          id: "double-digit",
          title: "Double Digit",
          type: "single",
          url: "",
          icon: "tabler:number-2",
        },
        {
          id: "single-panna",
          title: "Single Panna",
          type: "single",
          url: "",
          icon: "mdi:number-1-box",
        },
        {
          id: "double-panna",
          title: "Double Panna",
          type: "single",
          url: "",
          icon: "mdi:number-2-box",
        },
        {
          id: "triple-panna",
          title: "Triple Panna",
          type: "single",
          url: "",
          icon: "mdi:number-3-box",
        },
        {
          id: "half-sangam",
          title: "Half Sangam",
          type: "single",
          url: "",
          icon: "mdi:fraction-one-half",
        },
        {
          id: "full-sangam",
          title: "Full Sangam",
          type: "single",
          url: "",
          icon: "mdi:number-9-plus-box-multiple-outline",
        },
      ],
    },
    {
      id: "privacy-policy",
      title: "Privacy Policy",
      type: "single",
      url: "",
      icon: "mage:money-exchange",
    },
    {
      id: "terms-conditions",
      title: "Terms Conditions",
      type: "single",
      url: "",
      icon: "mage:money-exchange",
    },
    {
      id: "contact-us",
      title: "Contact Us",
      type: "single",
      url: "",
      icon: "mage:money-exchange",
    },
    {
      id: "delete-request",
      title: "Delete Request",
      type: "single",
      url: "",
      icon: "mage:money-exchange",
    },
  ],
};

export default menuItems;
